export const authStrings = {
  brand: "AI Interview Coach",
  closeLoginModal: "Close login modal",
  signIn: "Sign In",
  logout: "Logout",
  createAccountBadge: "Create account",
  welcomeBackBadge: "Welcome back",
  createAccountTitle: "Create your account",
  loginTitle: "Log in to continue",
  registrationDescription: "Register to save your learning progress, track interview practice, and unlock personalized coaching.",
  loginDescription: "Sign in to save your learning progress and continue your coaching journey.",
  fullName: "Full name",
  email: "Email address",
  password: "Password",
  confirmPassword: "Confirm password",
  submitRegister: "Create account",
  submitLogin: "Login",
  existingAccount: "Already have an account?",
  newAccount: "Need an account?",
  fullNameRequired: "Please enter your full name.",
  emailInvalid: "Please enter a valid email address.",
  passwordTooShort: "Password must be at least 8 characters.",
  passwordsDoNotMatch: "Passwords do not match.",
  duplicateEmail: "This email is already registered. Please log in instead.",
  invalidCredentials: "Invalid credentials. Please try again.",
  tryAgain: "Please try again.",
  signInTitle: "Sign In",
  registerTitle: "Register",
  hidePassword: "Hide password",
  showPassword: "Show password",
  hideConfirmPassword: "Hide confirm password",
  showConfirmPassword: "Show confirm password",
};